export interface HelpEntry {
	title: string;
	description: string;
	formula?: string;
	example?: string;
	insight?: string;
}

export const helpTexts: Record<string, HelpEntry> = {
	// ── EnergySummary: Grid Import ──
	gridImportToday: {
		title: 'Grid Import — Today',
		description:
			'Energy drawn from the electricity grid since midnight today. This is what your utility meter counts as consumption.',
		example: 'If your house uses 2 kWh in the morning before the sun rises, that all comes from the grid.',
		insight: 'Lower is better — it means more of your demand is met by solar or battery.'
	},
	gridImportMonth: {
		title: 'Grid Import — This Month',
		description:
			'Cumulative energy imported from the grid since the 1st of the current month. Useful for comparing against your monthly electricity bill.',
		insight: 'Compare this with your utility bill to verify the simulation matches reality.'
	},
	gridImportTotal: {
		title: 'Grid Import — Total',
		description:
			'Total energy imported from the grid across the entire simulation period.',
		insight: 'Divide by the number of days to get your average daily grid dependency.'
	},

	// ── EnergySummary: Energy Sources ──
	pvProduction: {
		title: 'PV Production',
		description:
			'Total electricity generated by your solar panels. This energy is either consumed directly by the home (self-consumption), stored in the battery, or exported to the grid.',
		insight: 'Peak production happens around midday on sunny days. Cloudy days may produce only 10–20% of rated capacity.'
	},
	selfConsumption: {
		title: 'Self-Consumption',
		description:
			'The portion of PV production used directly by the home at the moment it was generated, without going through the grid or battery.',
		formula: 'Self-Consumption % = Self-Consumed / PV Production × 100',
		example: 'If you produce 10 kWh and use 4 kWh directly, self-consumption is 40%.',
		insight: 'Higher self-consumption means less dependence on grid and export prices.'
	},
	gridExport: {
		title: 'Grid Export',
		description:
			'Surplus PV energy sent back to the grid because it exceeded home demand and battery capacity.',
		formula: 'Export = PV Production − Self-Consumption − Battery Charging',
		insight: 'Export revenue depends on spot prices. Exporting during negative-price hours can cost you money.'
	},

	// ── EnergySummary: Home ──
	homeDemand: {
		title: 'Home Demand',
		description:
			'Total energy consumed by the entire home, including the heat pump and all appliances.',
		formula: 'Home Demand = Heat Pump + Appliances',
		insight: 'This is your gross consumption regardless of where the energy comes from (grid, PV, or battery).'
	},
	heatPump: {
		title: 'Heat Pump',
		description:
			'Electricity consumed by the heat pump for heating/cooling. The COP (Coefficient of Performance) shows how much thermal energy you get per unit of electricity.',
		formula: 'COP = Thermal Output ÷ Electrical Input',
		example: 'COP 3.5 means for every 1 kWh of electricity, the heat pump delivers 3.5 kWh of heat.',
		insight: 'COP improves in milder weather. Running the heat pump during warmer hours saves energy.'
	},
	appliances: {
		title: 'Appliances',
		description:
			'Energy consumed by everything in the home except the heat pump — lights, fridge, cooking, electronics, etc.',
		formula: 'Appliances = Home Demand − Heat Pump',
		insight: 'This is your baseload. It tends to be fairly constant day-to-day.'
	},
	hpCost: {
		title: 'Heat Pump Cost',
		description:
			'Total electricity cost for running the heat pump, calculated using spot prices at the time of each reading.',
		formula: 'HP Cost = Σ (HP consumption × spot price) for each reading',
		insight: 'Shifting heat pump usage to cheaper hours can significantly reduce this cost.'
	},
	hpAvgPrice: {
		title: 'Avg HP Price',
		description:
			'Average price paid per kWh of heat pump electricity. Shows whether the heat pump tends to run during cheap or expensive hours.',
		formula: 'Avg HP Price = Total HP Cost ÷ Total HP Consumption',
		insight: 'Compare this with the overall average import price to see if the heat pump runs at favorable times.'
	},

	// ── EnergySummary: Battery Savings ──
	batterySaved: {
		title: 'Battery Saved',
		description:
			'Energy that would have been imported from the grid but was instead supplied by the battery. This is the direct energy benefit of having a battery.',
		formula: 'Saved = Grid Import (without battery) − Grid Import (with battery)',
		insight: 'The battery saves most when it discharges during peak-price hours.'
	},
	savingsPerKwh: {
		title: 'Savings per kWh',
		description:
			'How much grid import the battery saves relative to its capacity. Indicates how effectively the battery is being utilized.',
		formula: 'Savings/kWh = Battery Saved ÷ Battery Capacity',
		example: 'A 10 kWh battery saving 80 kWh of import = 8.0 kWh savings per kWh of capacity.',
		insight: 'Higher values mean the battery cycles frequently and is well-sized for your system.'
	},
	offGrid: {
		title: 'Off-Grid %',
		description:
			'Percentage of your total home demand covered by PV self-consumption and battery discharge, without relying on grid import.',
		formula: '(Self-Consumption + Battery Savings) ÷ Home Demand × 100',
		example: 'If demand is 20 kWh, self-consumption is 8 kWh, and battery provides 4 kWh, off-grid is 60%.',
		insight: '100% means complete energy independence. Typical PV + battery systems achieve 50–80%.'
	},

	// ── CostSummary: Energy Costs ──
	importCost: {
		title: 'Import Cost',
		description:
			'Total cost of electricity imported from the grid, calculated at spot prices for each reading interval.',
		formula: 'Import Cost = Σ (import kWh × spot price) for each reading',
		insight: 'This is what you pay the grid — the main number to minimize.'
	},
	exportRevenue: {
		title: 'Export Revenue',
		description:
			'Money earned by selling surplus PV energy back to the grid at spot prices.',
		formula: 'Export Revenue = Σ (export kWh × spot price × export coefficient)',
		insight: 'The export coefficient reflects the fraction of spot price your utility actually pays you.'
	},
	netCost: {
		title: 'Net Cost',
		description:
			'Your effective electricity cost after subtracting export revenue from import cost.',
		formula: 'Net Cost = Import Cost − Export Revenue',
		insight: 'A negative net cost means you earned more from exports than you spent on imports.'
	},

	// ── CostSummary: Strategy Comparison ──
	noBattery: {
		title: 'No Battery',
		description:
			'What your net electricity cost would be without any battery. Serves as the baseline for comparing battery strategies.',
		insight: 'The difference between this and the battery strategies shows the value of storage.'
	},
	selfConsumptionStrategy: {
		title: 'Self-Consumption Strategy',
		description:
			'Battery charges only from excess PV (never from grid) and discharges to offset grid import. Prioritizes using your own solar energy.',
		insight: 'Best when import prices are consistently high and you have good PV production.'
	},
	arbitrageStrategy: {
		title: 'Arbitrage Strategy',
		description:
			'Battery charges when spot prices are cheap (below daily P33) and discharges when expensive (above daily P67). Can charge from the grid.',
		formula: 'Charge when price ≤ 33rd percentile, discharge when price ≥ 67th percentile',
		insight: 'Works best with volatile spot prices and large daily price swings.'
	},
	netMetering: {
		title: 'Net Metering',
		description:
			'Legacy tariff where exported energy creates credits (kWh) that offset future imports at a configurable ratio (e.g., 0.8 = get back 80% of what you export).',
		formula: 'Credit = Export kWh × ratio. Import cost reduced by credits × distribution fee.',
		insight: 'Favorable when you export a lot — the ratio determines how much you get back.'
	},
	netBilling: {
		title: 'Net Billing',
		description:
			'Modern tariff where exports earn a PLN deposit at spot prices, and imports are charged at a fixed tariff rate.',
		formula: 'Deposit = Export kWh × spot price. Import cost = Import kWh × fixed tariff − deposit.',
		insight: 'Better than net metering when spot prices at export time are high relative to the fixed tariff.'
	},

	// ── CostSummary: ROI ──
	investment: {
		title: 'Investment',
		description: 'Estimated purchase cost of the battery system.',
		formula: 'Investment = Battery Capacity × Cost per kWh',
		example: 'A 10 kWh battery at 2000 PLN/kWh = 20,000 PLN investment.'
	},
	annualSavings: {
		title: 'Annual Savings',
		description:
			'Projected yearly savings from the battery, extrapolated from the simulation period so far.',
		formula: 'Annual Savings = (Total Savings ÷ Simulated Days) × 365',
		insight: 'This estimate improves as the simulation covers more days and seasons.'
	},
	payback: {
		title: 'Payback Period',
		description: 'How many years until the battery pays for itself through energy savings.',
		formula: 'Payback = Investment ÷ Annual Savings',
		example: 'Investment 20,000 PLN ÷ 4,000 PLN/year savings = 5.0 years.',
		insight: 'Most home batteries pay back in 5–12 years. Below 8 years is generally considered good.'
	},
	savingsPerCycle: {
		title: 'Savings per Cycle',
		description: 'Average PLN saved each time the battery completes a full charge-discharge cycle.',
		formula: 'Savings/Cycle = Total Battery Savings (PLN) ÷ Total Cycles',
		insight: 'Compare this with the battery degradation cost per cycle to check profitability.'
	},

	// ── CostSummary: Cheap Export ──
	cheapExportEnergy: {
		title: 'Cheap Export Energy',
		description:
			'Energy exported to the grid when the spot price was below your configured threshold. This energy earns little or negative revenue.',
		insight: 'Ideally this should be zero — a battery could store this energy for later use instead.'
	},
	cheapExportRevenue: {
		title: 'Cheap Export Revenue',
		description: 'Revenue earned from energy exported during cheap-price periods.',
		insight: 'If this is very low or negative, you are giving away energy. Consider increasing battery capacity.'
	},
	cheapExportPct: {
		title: 'Cheap Export %',
		description: 'What fraction of your total grid export happened during cheap-price periods.',
		formula: 'Cheap Export % = Cheap Export kWh ÷ Total Export kWh × 100',
		insight: 'A high percentage means most of your export happens at bad prices — battery storage would help.'
	},

	// ── CostSummary: EV Range ──
	avgImportPrice: {
		title: 'Avg Import Price',
		description: 'Average price paid per kWh of grid electricity across all import readings.',
		formula: 'Avg Import Price = Total Import Cost ÷ Total Import kWh',
		insight: 'Compare with the fixed tariff to see if spot pricing is working in your favor.'
	},
	evCost100km: {
		title: 'EV Cost per 100 km',
		description:
			'Estimated cost to drive an electric vehicle 100 km using grid electricity at your average import price.',
		formula: 'Cost/100km = Avg Import Price × 18 kWh (typical EV consumption)',
		example: 'At 0.50 PLN/kWh: 0.50 × 18 = 9.00 PLN per 100 km.',
		insight: 'Compare with petrol costs (~60–80 PLN/100km) to see EV savings.'
	},
	evKmFromExport: {
		title: 'km from Export',
		description:
			'How many kilometers an EV could drive using the energy you exported to the grid instead.',
		formula: 'km = (Export kWh ÷ 18 kWh/100km) × 100',
		insight: 'Shows the "driving potential" of your surplus PV — energy that could charge an EV instead of being exported.'
	},

	// ── BatteryStats ──
	cycles: {
		title: 'Battery Cycles',
		description:
			'Number of full charge-discharge cycles completed. One cycle = discharging the full usable capacity once (partial cycles are counted proportionally).',
		example: 'A 10 kWh battery discharged 5 kWh = 0.5 cycles.',
		insight: 'Most lithium batteries are rated for 4,000–6,000 cycles before reaching 80% capacity.'
	},
	effectiveCapacity: {
		title: 'Effective Capacity',
		description:
			'Current usable capacity after accounting for degradation. Decreases linearly as cycles accumulate.',
		formula: 'Effective = Original Capacity × (1 − Degradation%/100)',
		insight: 'When this drops significantly, the battery saves less energy per cycle.'
	},
	degradation: {
		title: 'Degradation',
		description:
			'Percentage of original capacity lost due to cycling. Based on a linear model from 100% to 80% over the configured cycle life.',
		formula: 'Degradation% = (Cycles ÷ Cycles-to-80%) × 20%',
		example: 'After 1000 cycles with 5000 cycle-to-80% rating: (1000/5000) × 20 = 4% degradation.',
		insight: 'Real batteries degrade faster with deep discharges and high temperatures.'
	},
	timeAtPower: {
		title: 'Time at Power',
		description:
			'Distribution of how long the battery spent at each power level. Negative values = charging, positive = discharging.',
		insight: 'Ideally shows a balanced charge/discharge pattern. Heavy idle time means the battery is oversized.'
	},
	timeAtSoC: {
		title: 'Time at SoC',
		description:
			'Distribution of how long the battery spent at each State of Charge level.',
		insight: 'Spending most time at 0% or 100% means the battery is undersized or poorly matched to your usage pattern.'
	},

	// ── BatteryConfig ──
	capacity: {
		title: 'Battery Capacity',
		description:
			'Total energy storage capacity of the battery in kilowatt-hours. This is the nameplate capacity before degradation.',
		example: 'A 10 kWh battery can store enough energy to run a 1 kW load for 10 hours.',
		insight: 'Typical home batteries range from 5–15 kWh. Match to your daily surplus PV for best results.'
	},
	maxPower: {
		title: 'Max Power',
		description:
			'Maximum rate at which the battery can charge or discharge, in kilowatts. Limits how fast energy flows in or out.',
		example: 'A 5 kW battery can fully charge a 10 kWh capacity in 2 hours.',
		insight: 'Higher power helps capture short PV peaks but costs more. Most homes need 3–5 kW.'
	},
	dischargeTo: {
		title: 'Discharge To',
		description:
			'Minimum State of Charge the battery will discharge to. Protects battery health by preventing deep discharge.',
		example: 'Set to 10% means the battery keeps at least 10% as reserve.',
		insight: 'Lower values give more usable capacity but accelerate degradation. 5–10% is typical.'
	},
	chargeTo: {
		title: 'Charge To',
		description:
			'Maximum State of Charge the battery will charge to. Keeping below 100% extends battery life.',
		example: 'Set to 90% means the battery stops charging at 90% full.',
		insight: 'Charging to 80–90% significantly extends cycle life for lithium batteries.'
	},
	degradationCycles: {
		title: 'Degradation Cycles',
		description:
			'Number of full cycles before the battery degrades to 80% of original capacity. Used for the linear degradation model.',
		example: 'A value of 6000 means after 6000 cycles the battery retains 80% capacity.',
		insight: 'LFP batteries typically achieve 5000–8000 cycles. NMC batteries around 2000–4000.'
	},

	// ── SimConfig ──
	exportCoefficient: {
		title: 'Export Coefficient',
		description:
			'Fraction of the spot price you actually receive when exporting energy to the grid. Accounts for utility margins and fees.',
		example: 'Set to 0.80 means you get 80% of the spot price for exported energy.',
		insight: 'Check your utility contract. Values range from 0.5 to 1.0 depending on the agreement.'
	},
	cheapExportThreshold: {
		title: 'Cheap Export Threshold',
		description:
			'Spot price (PLN/kWh) below which exported energy is considered "cheap". Used to flag exports that earn little revenue.',
		example: 'Set to 0.10 means any export at prices below 0.10 PLN/kWh is flagged.',
		insight: 'Set this to your break-even price to identify when exporting costs you money.'
	},
	tempOffset: {
		title: 'Temperature Offset',
		description:
			'Shifts the outdoor temperature used in NN predictions by this many degrees Celsius. Useful for testing warmer/cooler scenarios.',
		example: 'Set to +2 to simulate a 2°C warmer climate.',
		insight: 'Use this to estimate how climate changes or seasonal shifts affect energy usage.'
	},
	fixedTariff: {
		title: 'Fixed Tariff',
		description:
			'Fixed electricity price (PLN/kWh) used for the net billing tariff calculation. Represents the regulated retail rate.',
		insight: 'This is the price you pay for imports under net billing, regardless of spot price.'
	},
	distributionFee: {
		title: 'Distribution Fee',
		description:
			'Grid distribution fee (PLN/kWh) subtracted when using net metering credits. Represents the cost of transporting electricity.',
		formula: 'Net metering import cost = (Import − Credits) × Spot Price + Credits × Distribution Fee',
		insight: 'Higher distribution fees make net metering less attractive compared to self-consumption.'
	},
	netMeteringRatio: {
		title: 'Net Metering Ratio',
		description:
			'How much of each exported kWh you get back as credit. A ratio of 0.8 means exporting 10 kWh gives 8 kWh of credits.',
		example: 'Ratio 0.8: export 100 kWh → receive 80 kWh credits to offset future imports.',
		insight: 'Poland used 0.7–0.8 ratios. Higher ratios make net metering more valuable than net billing.'
	},
	batteryCost: {
		title: 'Battery Cost',
		description:
			'Estimated cost per kWh of battery capacity, used to calculate total investment and ROI.',
		example: 'At 2000 PLN/kWh, a 10 kWh battery costs 20,000 PLN.',
		insight: 'Battery prices have been falling. Current market ranges from 1500–3000 PLN/kWh installed.'
	},

	// ── TimeSeriesChart ──
	chartPower: {
		title: 'Power Chart',
		description:
			'Real-time power flow for selected sources. Positive values mean the home is consuming from that source; negative means energy is flowing back (e.g., battery charging or grid export).',
		insight: 'Toggle series with the legend buttons below. The chart auto-scales to fit all visible series.'
	},
	chartPrice: {
		title: 'Spot Price Chart',
		description:
			'Electricity spot price over time in PLN per kWh. Prices change hourly and can go negative during periods of oversupply.',
		insight: 'Compare price valleys with battery charge times to verify the arbitrage strategy is working.'
	},
	chartSoC: {
		title: 'Battery State of Charge',
		description:
			'Battery charge level as a percentage of effective capacity. The shaded area shows how full the battery is over time.',
		insight: 'A healthy pattern shows daily cycles between your discharge floor and charge ceiling.'
	},
	chartTemp: {
		title: 'Temperature Chart',
		description:
			'Outdoor temperature in degrees Celsius. When prediction mode is active, both actual and NN-predicted temperatures are shown for comparison.',
		insight: 'Temperature strongly affects heat pump consumption — warmer weather means higher COP and lower electricity use.'
	},

	// ── PredictionComparison ──
	nnPrediction: {
		title: 'NN Prediction',
		description:
			'Value predicted by the neural network for the current timestamp. The simulator chains two NNs: one predicts temperature from day/hour, the other predicts grid power from month/hour/temperature.',
		insight: 'Large deviations from actual values may indicate unusual weather or consumption patterns.'
	},
	mae: {
		title: 'MAE (Mean Absolute Error)',
		description:
			'Average prediction error across all samples so far. Lower is better — it shows how closely the NN matches real data.',
		formula: 'MAE = Σ |actual − predicted| ÷ number of samples',
		example: 'MAE of 200 W means the prediction is off by 200 W on average.',
		insight: 'MAE decreases as more training data is used. For home energy, MAE under 500 W is good.'
	},

	// ── HeatingAnalysis ──
	heatingAnalysis: {
		title: 'Heating Analysis',
		description:
			'Monthly breakdown of heat pump electricity consumption, thermal production, COP (Coefficient of Performance), cost, and average outdoor temperature.',
		insight: 'COP varies significantly by season — expect 4+ in summer and 2–3 in winter. Lower outdoor temps reduce COP.'
	},
	heatingCOP: {
		title: 'Monthly COP',
		description:
			'Coefficient of Performance for the heat pump in each month. Calculated as thermal production divided by electrical consumption.',
		formula: 'COP = Production (kWh) ÷ Consumption (kWh)',
		example: 'COP 3.5 means for every 1 kWh of electricity, the heat pump produced 3.5 kWh of heat.',
		insight: 'Green (≥3.5) is excellent, amber (2.5–3.5) is typical for cold weather, red (<2.5) suggests very cold conditions or a problem.'
	},

	// ── AnomalyLog ──
	anomalyLog: {
		title: 'Consumption Anomalies',
		description:
			'Days where actual grid consumption deviated significantly from what the neural network predicted. Helps identify unusual consumption patterns.',
		insight: 'Anomalies can indicate guests, equipment problems, unusual weather, or changes in routine.'
	},
	anomalyDeviation: {
		title: 'Deviation %',
		description:
			'How much the actual grid import differed from the NN prediction, as a percentage of predicted consumption.',
		formula: 'Deviation = (Actual − Predicted) ÷ Predicted × 100%',
		example: '+50% means 50% more grid import than predicted. −30% means 30% less.',
		insight: 'Red (positive) means higher-than-expected consumption. Blue (negative) means lower. Only days with >20% deviation are shown.'
	}
};
